class ModeAvail:
    """Lookup table of which game mode ids are supported on which map ids."""

    _map_id_to_mode_ids: dict[str, list[str]] = {
        "MP_001": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_003": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_007": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_011": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_012": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_013": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_017": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_018": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "MP_Subway": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP1_001": [
            "ConquestAssaultLarge0",
            "ConquestAssaultSmall0",
            "ConquestAssaultSmall1",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP1_002": [
            "ConquestAssaultSmall0",
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP1_003": [
            "ConquestAssaultLarge0",
            "ConquestAssaultSmall0",
            "ConquestAssaultSmall1",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP1_004": [
            "ConquestAssaultLarge0",
            "ConquestAssaultSmall0",
            "ConquestAssaultSmall1",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP2_Palace": [
            "Domination0",
            "GunMaster0",
            "SquadDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP2_Office": [
            "Domination0",
            "GunMaster0",
            "SquadDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP2_Factory": [
            "Domination0",
            "GunMaster0",
            "SquadDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP2_Skybar": [
            "Domination0",
            "GunMaster0",
            "SquadDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP3_Alborz": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TankSuperiority0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP3_Shield": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TankSuperiority0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP3_Desert": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TankSuperiority0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP3_Valley": [
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TankSuperiority0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP4_Parl": [
            "ConquestLarge0",
            "ConquestSmall0",
            "GunMaster0",
            "RushLarge0",
            "Scavenger0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP4_Quake": [
            "ConquestLarge0",
            "ConquestSmall0",
            "GunMaster0",
            "RushLarge0",
            "Scavenger0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP4_FD": [
            "ConquestLarge0",
            "ConquestSmall0",
            "GunMaster0",
            "RushLarge0",
            "Scavenger0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP4_Rubble": [
            "ConquestAssaultLarge0",
            "ConquestAssaultSmall0",
            "GunMaster0",
            "RushLarge0",
            "Scavenger0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP5_001": [
            "AirSuperiority0",
            "CaptureTheFlag0",
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP5_002": [
            "AirSuperiority0",
            "CaptureTheFlag0",
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP5_003": [
            "AirSuperiority0",
            "CaptureTheFlag0",
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
        "XP5_004": [
            "AirSuperiority0",
            "CaptureTheFlag0",
            "ConquestLarge0",
            "ConquestSmall0",
            "RushLarge0",
            "SquadDeathMatch0",
            "SquadRush0",
            "TeamDeathMatch0",
            "TeamDeathMatchC0",
        ],
    }

    _mode_id_to_map_ids: dict[str, list[str]] = {}
    for _map_id, _mode_ids in _map_id_to_mode_ids.items():
        for _mode_id in _mode_ids:
            _mode_id_to_map_ids.setdefault(_mode_id, []).append(_map_id)
    del _map_id, _mode_ids, _mode_id

    @classmethod
    def supported_game_modes_for_map_id(cls, map_id: str) -> list[str]:
        return list(cls._map_id_to_mode_ids[map_id])

    @classmethod
    def maps_supporting_game_mode(cls, mode_id: str) -> list[str]:
        return list(cls._mode_id_to_map_ids[mode_id])
