from config.config_item import ConfigDeliveryType, ConfigItem, ConfigType, Range
from config.toml_config import Config
from game.cs2.config_index import ConfigIndex


def build_game_defaults() -> Config[ConfigIndex]:
    return {
        ConfigIndex.SELECTED_MAP: ConfigItem(
            name="selected_map",
            visible_name="Selected map",
            type=ConfigType.STRING_LIST,
            config_type=ConfigDeliveryType.COMMAND_LINE,
            tooltip="The currently selected map, one of the maps in the selected map group",
            value="",  #  will be filled in later
            # allowed_values=... will be filled in later
        ),
        ConfigIndex.SELECTED_MAP_GROUP: ConfigItem(
            name="selected_map_group",
            visible_name="Selected map group",
            type=ConfigType.STRING_LIST,
            config_type=ConfigDeliveryType.COMMAND_LINE,
            tooltip='The currently selected map group, if "ALL" all maps are included',
            value="ALL",
            # allowed_values=... will be filled in later
        ),
        ConfigIndex.GAME_MODE: ConfigItem(
            name="game_mode",
            visible_name="Game mode",
            type=ConfigType.STRING_LIST,
            config_type=ConfigDeliveryType.COMMAND_LINE,
            tooltip="Currently selected game mode",
            value="Casual",
            allowed_values=[
                "Casual",
                "Competitive",
                "ArmsRace",
                "DeathMatch",
                "Demolition",
            ],
        ),
        ConfigIndex.PLAYER_COUNT: ConfigItem(
            name="maxplayers",
            visible_name="Players",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.COMMAND_LINE,
            tooltip="Total player slots — adjust to your group size",
            value=10,
            range=Range(min_value=1, max_value=64),
        ),
        # -- Network --
        ConfigIndex.HOSTNAME: ConfigItem(
            name="hostname",
            visible_name="Hostname",
            type=ConfigType.STRING,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Server name shown in the server browser",
            value="My LAN Server",
        ),
        ConfigIndex.SV_LAN: ConfigItem(
            name="sv_lan",
            visible_name="LAN only",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="LAN only — not visible on the internet server browser",
            value=True,
        ),
        ConfigIndex.SV_PASSWORD: ConfigItem(
            name="sv_password",
            visible_name="Server password",
            type=ConfigType.MASKED_STRING,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Password required to join; empty means no password",
            value="",
        ),
        ConfigIndex.SV_VISIBLEMAXPLAYERS: ConfigItem(
            name="sv_visiblemaxplayers",
            visible_name="Visible max players",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="-1 = use the Players setting",
            value=-1,
            range=Range(min_value=-1, max_value=64),
        ),
        # -- Bots --
        ConfigIndex.BOT_DIFFICULTY: ConfigItem(
            name="bot_difficulty",
            visible_name="Bot difficulty",
            type=ConfigType.STRING_LIST,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Bot skill level",
            value="Normal",
            allowed_values=["Harmless", "Easy", "Normal", "Hard", "Harder", "Expert"],
        ),
        ConfigIndex.BOT_QUOTA: ConfigItem(
            name="bot_quota",
            visible_name="Bot quota",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Number of bots to maintain",
            value=4,
            range=Range(min_value=0, max_value=64),
        ),
        ConfigIndex.BOT_QUOTA_MODE: ConfigItem(
            name="bot_quota_mode",
            visible_name="Bot quota mode",
            type=ConfigType.STRING_LIST,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="fill = top off empty slots, normal = fixed count, match = mirror human count",
            value="fill",
            allowed_values=["fill", "normal", "match"],
        ),
        ConfigIndex.BOT_CHATTER: ConfigItem(
            name="bot_chatter",
            visible_name="Bot chatter",
            type=ConfigType.STRING_LIST,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Bot radio chatter verbosity",
            value="off",
            allowed_values=["off", "radio", "minimal", "normal"],
        ),
        ConfigIndex.BOT_WALK: ConfigItem(
            name="bot_walk",
            visible_name="Bots always walk",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Bots always walk instead of run",
            value=False,
        ),
        ConfigIndex.BOT_JOIN_AFTER_PLAYER: ConfigItem(
            name="bot_join_after_player",
            visible_name="Bots join after player",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="When enabled, bots only fill in after a human player joins",
            value=True,
        ),
        ConfigIndex.BOT_ALL_WEAPONS: ConfigItem(
            name="bot_all_weapons",
            visible_name="Bots use all weapons",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Let bots use grenades and the full weapon loadout",
            value=True,
        ),
        ConfigIndex.BOT_AUTO_DIFFICULTY: ConfigItem(
            name="bot_auto_difficulty",
            visible_name="Bot auto difficulty",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Auto-scale bot difficulty to player skill",
            value=False,
        ),
        # -- Match / round rules --
        ConfigIndex.MP_ROUNDTIME: ConfigItem(
            name="mp_roundtime",
            visible_name="Round time",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Round length in minutes",
            value=2,
            range=Range(min_value=1, max_value=60),
        ),
        ConfigIndex.MP_FREEZETIME: ConfigItem(
            name="mp_freezetime",
            visible_name="Freeze time",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Freeze time at round start, in seconds",
            value=5,
        ),
        ConfigIndex.MP_BUYTIME: ConfigItem(
            name="mp_buytime",
            visible_name="Buy time",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Buy period length, in seconds",
            value=20,
        ),
        ConfigIndex.MP_MAXROUNDS: ConfigItem(
            name="mp_maxrounds",
            visible_name="Max rounds",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Rounds per map; 0 = unlimited (good for casual LAN nights)",
            value=0,
            range=Range(min_value=0, max_value=24),
        ),
        ConfigIndex.MP_HALFTIME: ConfigItem(
            name="mp_halftime",
            visible_name="Halftime",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Swap sides at half",
            value=True,
        ),
        ConfigIndex.MP_OVERTIME_ENABLE: ConfigItem(
            name="mp_overtime_enable",
            visible_name="Overtime enabled",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Enable overtime if the match is tied",
            value=True,
        ),
        ConfigIndex.MP_OVERTIME_MAXROUNDS: ConfigItem(
            name="mp_overtime_maxrounds",
            visible_name="Overtime max rounds",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Number of overtime rounds",
            value=6,
            range=Range(min_value=0, max_value=24),
        ),
        ConfigIndex.MP_STARTMONEY: ConfigItem(
            name="mp_startmoney",
            visible_name="Start money",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Starting money in round 1",
            value=800,
            range=Range(min_value=0, max_value=16000),
        ),
        ConfigIndex.MP_MAXMONEY: ConfigItem(
            name="mp_maxmoney",
            visible_name="Max money",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Money cap",
            value=16000,
        ),
        ConfigIndex.MP_FRIENDLYFIRE: ConfigItem(
            name="mp_friendlyfire",
            visible_name="Friendly fire",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Off is the recommended default for casual play with friends",
            value=False,
        ),
        ConfigIndex.MP_AUTOTEAMBALANCE: ConfigItem(
            name="mp_autoteambalance",
            visible_name="Auto team balance",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Auto-balance teams between rounds",
            value=False,
        ),
        ConfigIndex.MP_LIMITTEAMS: ConfigItem(
            name="mp_limitteams",
            visible_name="Team size limit",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Max player-count difference allowed between teams",
            value=20,
            range=Range(min_value=0, max_value=20),
        ),
        ConfigIndex.MP_WARMUPTIME: ConfigItem(
            name="mp_warmuptime",
            visible_name="Warmup time",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Warmup length, in seconds",
            value=1,
            range=Range(min_value=1, max_value=900),
        ),
        ConfigIndex.MP_WARMUP_PAUSETIMER: ConfigItem(
            name="mp_warmup_pausetimer",
            visible_name="Warmup pause timer",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="When enabled, warmup won't end until manually started",
            value=False,
        ),
        ConfigIndex.MP_RESPAWN_ON_DEATH_CT: ConfigItem(
            name="mp_respawn_on_death_ct",
            visible_name="CT respawn on death",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Counter terrorists respawn on death (fun/casual mode)",
            value=False,
        ),
        ConfigIndex.MP_RESPAWN_ON_DEATH_T: ConfigItem(
            name="mp_respawn_on_death_t",
            visible_name="Terrorists respawn on death",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Ts respawn on death (fun/casual mode)",
            value=False,
        ),
        # -- Economy / weapons --
        ConfigIndex.MP_FREE_ARMOR: ConfigItem(
            name="mp_free_armor",
            visible_name="Free armor",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Give free armor every round",
            value=False,
        ),
        ConfigIndex.MP_AFTERROUNDMONEY: ConfigItem(
            name="mp_afterroundmoney",
            visible_name="After-round money",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Bonus flat cash awarded at round end",
            value=0,
        ),
        ConfigIndex.MP_DEATH_DROP_GUN: ConfigItem(
            name="mp_death_drop_gun",
            visible_name="Drop gun on death",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Drop weapon on death",
            value=True,
        ),
        ConfigIndex.MP_DEATH_DROP_GRENADE: ConfigItem(
            name="mp_death_drop_grenade",
            visible_name="Drop grenades on death",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Drop grenades on death",
            value=True,
        ),
        # -- Voice / comms --
        ConfigIndex.SV_VOICEENABLE: ConfigItem(
            name="sv_voiceenable",
            visible_name="Voice chat enabled",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Enable voice chat",
            value=True,
        ),
        ConfigIndex.SV_ALLTALK: ConfigItem(
            name="sv_alltalk",
            visible_name="All talk",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="All players hear each other regardless of team (fun for LAN)",
            value=True,
        ),
        ConfigIndex.SV_DEADTALK: ConfigItem(
            name="sv_deadtalk",
            visible_name="Dead talk",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Dead players can be heard by the living",
            value=True,
        ),
        # -- Cheats / security --
        ConfigIndex.SV_CHEATS: ConfigItem(
            name="sv_cheats",
            visible_name="Cheats enabled",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Keep off unless you want to use cheat-only commands",
            value=False,
        ),
        ConfigIndex.SV_PURE: ConfigItem(
            name="sv_pure",
            visible_name="Pure server",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Off allows custom content/skins on LAN, with no consistency checks",
            value=False,
        ),
        ConfigIndex.SV_ALLOW_WAIT_COMMAND: ConfigItem(
            name="sv_allow_wait_command",
            visible_name="Allow wait command",
            type=ConfigType.BOOLEAN,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Disable the wait-command spam exploit",
            value=False,
        ),
        # -- Performance / tickrate --
        ConfigIndex.SV_MAXUPDATERATE: ConfigItem(
            name="sv_maxupdaterate",
            visible_name="Max update rate",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Maximum network update rate; LAN can push this high",
            value=128,
            range=Range(min_value=10, max_value=128),
        ),
        ConfigIndex.SV_MINUPDATERATE: ConfigItem(
            name="sv_minupdaterate",
            visible_name="Min update rate",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Minimum network update rate",
            value=64,
            range=Range(min_value=10, max_value=128),
        ),
        ConfigIndex.SV_MAXCMDRATE: ConfigItem(
            name="sv_maxcmdrate",
            visible_name="Max cmd rate",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Maximum command rate; LAN can push this high",
            value=128,
            range=Range(min_value=10, max_value=128),
        ),
        ConfigIndex.SV_MINCMDRATE: ConfigItem(
            name="sv_mincmdrate",
            visible_name="Min cmd rate",
            type=ConfigType.INTEGER,
            config_type=ConfigDeliveryType.SERVER_CFG_FILE,
            tooltip="Minimum command rate",
            value=64,
            range=Range(min_value=10, max_value=128),
        ),
    }
