"""
cvar_info.py

Auto-generated by analyzing Valve's own gamemode_<mode>.cfg files
(shipped in every CS2 dedicated server install's game/csgo/cfg/) for
the 5 game modes sgsl's own GAME_MODE item offers (see its
allowed_values in config_defaults.py): Casual, Competitive, ArmsRace,
Demolition, DeathMatch.

Every cvar assignment found in at least one of those 5 files falls
into exactly one of:
  - COMMON_CVARS -- present (with a possibly different value) in all 5.
  - GAME_MODE_SPECIFIC_CVARS -- present in only some of them, mapped
    to exactly which.

CORE_CVARS is different: it's every sgsl ConfigItem in config_defaults.py
marked config_type=SERVER_CFG_FILE (i.e. one sgsl itself writes into a
gamemode_<mode>.cfg -- see CS2Game._update_gamemode_cfg()) whose cvar
name doesn't appear in any of the 5 files at all -- server identity/
security settings (hostname, sv_password, sv_lan, sv_cheats,
rcon_password, ...) and match-vote settings that Valve's own stock
gamemode cfgs simply never set, plus a handful of gameplay cvars that
happen not to appear in any of the 5 either. Unlike the two tables
above (derived purely from parsing those files), this one is derived
from sgsl's own config items, so it isn't "found valid for every game
mode" so much as "not gamemode-specific at all, applies regardless."
Every entry has been independently confirmed (web search against
community CS2 cvar references, e.g. totalcsgo.com/csdb.gg) to be a
real, currently-valid CS2 console variable -- none were invented or
deprecated, so no config item needed to be removed.

This is a point-in-time snapshot, not derived at runtime -- regenerate
by re-analyzing a fresh set of gamemode_<mode>.cfg files (e.g. after a
CS2 update changes what a stock gamemode ships) rather than hand-
editing these tables.
"""

from __future__ import annotations

from typing import Optional

# Cvars present in all 5 of CS2's sgsl-selectable game modes' own
# stock gamemode_<mode>.cfg files.
COMMON_CVARS: frozenset[str] = frozenset(
    {
        "ammo_grenade_limit_flashbang",
        "ammo_grenade_limit_total",
        "bot_autodifficulty_threshold_high",
        "bot_autodifficulty_threshold_low",
        "bot_chatter",
        "bot_defer_to_human_goals",
        "bot_defer_to_human_items",
        "bot_difficulty",
        "bot_quota",
        "bot_quota_mode",
        "cash_player_bomb_defused",
        "cash_player_bomb_planted",
        "cash_player_damage_hostage",
        "cash_player_interact_with_hostage",
        "cash_player_killed_enemy_default",
        "cash_player_killed_enemy_factor",
        "cash_player_killed_hostage",
        "cash_player_killed_teammate",
        "cash_player_rescued_hostage",
        "cash_team_elimination_bomb_map",
        "cash_team_elimination_hostage_map_ct",
        "cash_team_elimination_hostage_map_t",
        "cash_team_hostage_alive",
        "cash_team_hostage_interaction",
        "cash_team_loser_bonus",
        "cash_team_loser_bonus_consecutive_rounds",
        "cash_team_planted_bomb_but_defused",
        "cash_team_rescued_hostage",
        "cash_team_terrorist_win_bomb",
        "cash_team_win_by_defusing_bomb",
        "cash_team_win_by_hostage_rescue",
        "cash_team_win_by_time_running_out_bomb",
        "cash_team_win_by_time_running_out_hostage",
        "ff_damage_reduction_bullets",
        "ff_damage_reduction_grenade",
        "ff_damage_reduction_grenade_self",
        "ff_damage_reduction_other",
        "mp_afterroundmoney",
        "mp_buy_anywhere",
        "mp_buy_during_immunity",
        "mp_buytime",
        "mp_ct_default_melee",
        "mp_ct_default_primary",
        "mp_ct_default_secondary",
        "mp_death_drop_defuser",
        "mp_death_drop_grenade",
        "mp_death_drop_gun",
        "mp_default_team_winner_no_objective",
        "mp_defuser_allocation",
        "mp_display_kill_assists",
        "mp_force_pick_time",
        "mp_forcecamera",
        "mp_free_armor",
        "mp_freezetime",
        "mp_friendlyfire",
        "mp_halftime",
        "mp_match_can_clinch",
        "mp_maxmoney",
        "mp_maxrounds",
        "mp_playercashawards",
        "mp_randomspawn",
        "mp_randomspawn_los",
        "mp_respawn_immunitytime",
        "mp_respawn_on_death_ct",
        "mp_respawn_on_death_t",
        "mp_roundtime",
        "mp_roundtime_defuse",
        "mp_roundtime_hostage",
        "mp_solid_teammates",
        "mp_startmoney",
        "mp_t_default_melee",
        "mp_t_default_primary",
        "mp_t_default_secondary",
        "mp_teamcashawards",
        "mp_timelimit",
        "mp_warmuptime",
        "mp_weapons_allow_map_placed",
        "mp_weapons_allow_zeus",
        "mp_weapons_glow_on_ground",
        "mp_win_panel_display_time",
        "spec_freeze_time",
        "sv_allow_votes",
        "sv_deadtalk",
        "sv_gameinstructor_enable",
        "sv_ignoregrenaderadio",
        "sv_infinite_ammo",
        "sv_talk_enemy_dead",
        "sv_talk_enemy_living",
    }
)

# Cvars present in only some game modes' stock gamemode_<mode>.cfg
# files, mapped to exactly which ones.
GAME_MODE_SPECIFIC_CVARS: dict[str, frozenset[str]] = {
    "cash_team_bonus_shorthanded": frozenset({"Casual", "Competitive", "Demolition"}),
    "contributionscore_assist_reqs": frozenset({"Casual", "Competitive"}),
    "contributionscore_kill_reqs": frozenset({"Casual", "Competitive"}),
    "contributionscore_participation": frozenset({"Casual"}),
    "healthshot_health": frozenset({"ArmsRace", "DeathMatch"}),
    "healthshot_healthboost_time": frozenset({"ArmsRace", "DeathMatch"}),
    "mp_bot_ai_bt": frozenset({"ArmsRace", "DeathMatch"}),
    "mp_buy_allow_grenades": frozenset({"ArmsRace", "DeathMatch"}),
    "mp_limitteams": frozenset({"DeathMatch"}),
    "mp_promoted_item_enabled": frozenset({"Casual", "Competitive", "DeathMatch"}),
    "mp_round_restart_delay": frozenset({"Casual", "Demolition"}),
    "mp_starting_losses": frozenset({"Competitive"}),
    "mp_teammates_are_enemies": frozenset({"ArmsRace", "DeathMatch"}),
    "mp_technical_timeout_duration_s": frozenset({"Competitive"}),
    "mp_technical_timeout_per_team": frozenset({"Competitive"}),
    "mp_warmuptime_all_players_connected": frozenset({"Competitive"}),
    "mp_weapons_allow_typecount": frozenset({"ArmsRace", "Casual", "DeathMatch"}),
    "r_decals_overide_fadestarttime_params": frozenset({"ArmsRace", "DeathMatch"}),
    "spec_replay_enable": frozenset({"Casual", "Competitive", "Demolition"}),
    "sv_allow_annotations_access_level": frozenset(
        {"ArmsRace", "Casual", "Competitive", "DeathMatch"}
    ),
    "sv_annotation_limits_max_rounds_per_half": frozenset({"Casual"}),
    "sv_auto_full_alltalk_during_warmup_half_end": frozenset({"Competitive"}),
    "sv_disconnected_players_cleanup_delay": frozenset({"ArmsRace", "DeathMatch"}),
    "sv_grenade_trajectory_time_spectator": frozenset({"Competitive"}),
    "sv_health_approach_enabled": frozenset({"ArmsRace", "DeathMatch"}),
    "sv_health_approach_speed": frozenset({"ArmsRace", "DeathMatch"}),
    "sv_max_deathmatch_respawns_per_tick": frozenset({"ArmsRace", "DeathMatch"}),
    "sv_minimum_desired_chicken_count": frozenset(
        {"ArmsRace", "Casual", "Competitive", "DeathMatch"}
    ),
    "sv_sellback_enabled": frozenset({"ArmsRace", "Casual", "Competitive", "DeathMatch"}),
    "sv_vote_to_changelevel_before_match_point": frozenset({"Casual"}),
    "tv_delay": frozenset({"Casual", "Competitive", "DeathMatch", "Demolition"}),
}

# sgsl's own SERVER_CFG_FILE config items whose cvar name isn't in
# COMMON_CVARS or GAME_MODE_SPECIFIC_CVARS -- see module docstring.
CORE_CVARS: frozenset[str] = frozenset(
    {
        "bot_all_weapons",
        "bot_join_after_player",
        "bot_walk",
        "hostname",
        "mp_autoteambalance",
        "mp_endmatch_votenextleveltime",
        "mp_endmatch_votenextmap",
        "mp_match_restart_delay",
        "mp_overtime_enable",
        "mp_overtime_maxrounds",
        "mp_team_intro_time",
        "mp_warmup_pausetimer",
        "rcon_password",
        "sv_alltalk",
        "sv_cheats",
        "sv_lan",
        "sv_password",
        "sv_visiblemaxplayers",
        "sv_voiceenable",
    }
)


def is_common_cvar(name: str) -> bool:
    """True if `name` is present in every game mode's own stock cfg
    (see COMMON_CVARS)."""
    return name in COMMON_CVARS


def is_core_cvar(name: str) -> bool:
    """True if `name` is a core (not gamemode-specific) cvar -- see
    CORE_CVARS."""
    return name in CORE_CVARS


def is_gamemode_specific_cvar(name: str) -> bool:
    """True if `name` is restricted to a specific set of game modes --
    see GAME_MODE_SPECIFIC_CVARS. Use game_modes_for_cvar() to get
    that set."""
    return name in GAME_MODE_SPECIFIC_CVARS


def game_modes_for_cvar(name: str) -> Optional[frozenset[str]]:
    """The specific set of game modes `name` is valid for, if it's a
    game-mode-specific cvar (see GAME_MODE_SPECIFIC_CVARS) -- None if
    it's common to every mode (see is_common_cvar()), core (see
    is_core_cvar()), or isn't a cvar this module has any data for --
    in every one of those cases it isn't restricted to any particular
    subset of game modes."""
    return GAME_MODE_SPECIFIC_CVARS.get(name)


def is_cvar_valid_for_game_mode(name: str, game_mode: str) -> bool:
    """True if `name` is known to apply to `game_mode` -- because it's
    common to every mode, because it's a core cvar that isn't tied to
    any particular mode at all, or because it's specific to a set of
    modes that includes this one. A cvar this module has no data for
    at all (not in COMMON_CVARS, CORE_CVARS, or
    GAME_MODE_SPECIFIC_CVARS) is treated as valid too, since the
    absence of data isn't evidence of restriction."""
    if is_common_cvar(name) or is_core_cvar(name):
        return True
    modes = GAME_MODE_SPECIFIC_CVARS.get(name)
    if modes is None:
        return True
    return game_mode in modes
